{
    "name": "PassionTech ERP",
    "version": "19.0.1.0.0",
    "summary": "Complete approved PassionTech Phase-1 ERP bootstrap",
    "category": "PassionTech",
    "author": "Passion Technology",
    "license": "AGPL-3",
    "depends": [
        "passiontech_financial_reports",
        "l10n_et",
        "purchase_stock",
        "stock_account",
        "stock_landed_costs",
        "product_expiry",
        "stock_picking_batch",
        "stock_dropshipping",
        "sale_margin",
        "sale_loyalty",
        "sale_product_matrix",
        "purchase_product_matrix",
        "purchase_requisition",
        "account_debit_note",
        "account_check_printing",
        "crm",
        "delivery",
        "account_asset_management",
        "account_financial_report",
        "account_reconcile_oca",
        "account_statement_base",
        "account_statement_import_base",
        "account_statement_import_file",
        "account_statement_import_file_reconcile_oca",
        "account_statement_import_sheet_file",
        "account_statement_import_sheet_file_xlsx"
    ],
    "data": [],
    "installable": True,
    "application": True,
    "auto_install": False
}
